name: 编译并部署

on:
    push:
      branches:
        - dev
    release:
      types:
        - published

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: 检查仓库
              uses: actions/checkout@v4.1.1
        
            - name: 安装 Node.js
              uses: actions/setup-node@v4.0.0
              with:
                node-version: 18.x
            
            - name: 复制 .env.example
              run: |
                if [ ! -f ".env" ]; then
                  cp .env.example .env
                  echo ".env file does not exist. Copied .env.example to .env."
                else
                  echo ".env file already exists. Skipping the copy step."
                fi
            
            - name: 安装 pnpm
              run: npm install -g pnpm
            
            - name: 安装依赖
              run: pnpm install
            
            - name: 编译项目
              run: pnpm build
            
            - name: 部署到服务器
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                source: dist/*
                target: /home/Jerry_FaGe/home
                strip_components: 1